version: 2
jobs:

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
          command: mvn clean install
      - save_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          command: mkdir ~/test-results
      - run:
          command: find ~/repo -type f -regex ".*/surefire-reports/.*xml" -exec ln {} ~/test-results/ \;
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results